### ISSUE TITLE
Proper behavior at ingest of list

### ISSUE THREAD

**Issue by Pikus16** [tinker-engine/tinker-engine#127]
@waxlamp @nrsyed What is the desired behavior for something like this?
![image](https://user-images.githubusercontent.com/12414995/108416624-f7eaf580-71fc-11eb-8f79-61057f41cb62.png)

Right now the output is one single config:
{'foo': 3, 'bar': [{'iterate': [4, 5, 6]}, {'iterate': [7, 8]}]}

I think for iterate this is fine (maybe throw a warning), we shouldn't have multiple iterate directives per variable.

However, for other directives, it may make sense to pass multiple instances of it. For example. for smqtk: 
![image](https://user-images.githubusercontent.com/12414995/108417111-91b2a280-71fd-11eb-8372-8321215669de.png)

1) Would we want to support the ability to handle list of directives under one key-value pair?
2) If yes, should this support be handled by each directive (ex: is_iterate or is_smqtk should account for this) or should it be handled at a more general level?

**Comment by waxlamp** [comment]
> @waxlamp @nrsyed What is the desired behavior for something like this?
> ![image](https://user-images.githubusercontent.com/12414995/108416624-f7eaf580-71fc-11eb-8f79-61057f41cb62.png)
> 
> Right now the output is one single config:
> {'foo': 3, 'bar': [{'iterate': [4, 5, 6]}, {'iterate': [7, 8]}]}
> 
> I think for iterate this is fine (maybe throw a warning), we shouldn't have multiple iterate directives per variable.

I think this is the correct behavior, for two reasons. One is what you said, repeating `iterate` per variable isn't allowed. The other is more general (and maybe more fundamental here): we don't allow `iterate` directives inside list elements. There, it's interpreted as a literal object instead of a special directive.

If there was demand for it, though, we could interpret this to be generating multiple runs with different lists. In your example, we would get six runs with `bar` set to `[4, 7]`, `[4, 8]`, `[5, 7]`, etc. But this doesn't seem to be something we need to offer.

> 
> However, for other directives, it may make sense to pass multiple instances of it. For example. for smqtk:
> ![image](https://user-images.githubusercontent.com/12414995/108417111-91b2a280-71fd-11eb-8372-8321215669de.png)
> 
> 1. Would we want to support the ability to handle list of directives under one key-value pair?
> 2. If yes, should this support be handled by each directive (ex: is_iterate or is_smqtk should account for this) or should it be handled at a more general level?

I'm not sure I understand your example (and therefore, your followup questions). If you are saying that we should support `smqtk` directives appearing in a list, then I agree.

One task here is to collect all of these examples as tests, and then ensure that we are providing the correct semantics for them organically. This is something we can discuss at tomorrow's standup.

**Comment by Pikus16** [comment]
Closing the loop on this (from our previous conversation - just wanted to make sure it was documented).

We've decided that it makes sense to have two classes of directives, a "preprocess" class of directives and "process" (naming of these classes could use some work). The "preprocess" directives actually change the config (ex: "iterate") while the "process" directives instead are used to define and direct items (ex: "smqtk"). The "preprocess" directives are handled first, followed by the "process" ones, because we fundamentally expect different interactions between the two. 

So in the above example, we'd first go through, roll out all the "iterate" directives, and then let the parser handle all the "smqtk directives"
